// Generated by gencpp from file location_monitor/location_monitor_generate_messages_cpp.msg
// DO NOT EDIT!


#ifndef LOCATION_MONITOR_MESSAGE_LOCATION_MONITOR_GENERATE_MESSAGES_CPP_H
#define LOCATION_MONITOR_MESSAGE_LOCATION_MONITOR_GENERATE_MESSAGES_CPP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace location_monitor
{
template <class ContainerAllocator>
struct location_monitor_generate_messages_cpp_
{
  typedef location_monitor_generate_messages_cpp_<ContainerAllocator> Type;

  location_monitor_generate_messages_cpp_()
    {
    }
  location_monitor_generate_messages_cpp_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::location_monitor::location_monitor_generate_messages_cpp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::location_monitor::location_monitor_generate_messages_cpp_<ContainerAllocator> const> ConstPtr;

}; // struct location_monitor_generate_messages_cpp_

typedef ::location_monitor::location_monitor_generate_messages_cpp_<std::allocator<void> > location_monitor_generate_messages_cpp;

typedef boost::shared_ptr< ::location_monitor::location_monitor_generate_messages_cpp > location_monitor_generate_messages_cppPtr;
typedef boost::shared_ptr< ::location_monitor::location_monitor_generate_messages_cpp const> location_monitor_generate_messages_cppConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::location_monitor::location_monitor_generate_messages_cpp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::location_monitor::location_monitor_generate_messages_cpp_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace location_monitor

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'location_monitor': ['/home/basti/catkin_ws/src/location_monitor/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::location_monitor::location_monitor_generate_messages_cpp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::location_monitor::location_monitor_generate_messages_cpp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::location_monitor::location_monitor_generate_messages_cpp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::location_monitor::location_monitor_generate_messages_cpp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::location_monitor::location_monitor_generate_messages_cpp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::location_monitor::location_monitor_generate_messages_cpp_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::location_monitor::location_monitor_generate_messages_cpp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::location_monitor::location_monitor_generate_messages_cpp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::location_monitor::location_monitor_generate_messages_cpp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "location_monitor/location_monitor_generate_messages_cpp";
  }

  static const char* value(const ::location_monitor::location_monitor_generate_messages_cpp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::location_monitor::location_monitor_generate_messages_cpp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::location_monitor::location_monitor_generate_messages_cpp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::location_monitor::location_monitor_generate_messages_cpp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct location_monitor_generate_messages_cpp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::location_monitor::location_monitor_generate_messages_cpp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::location_monitor::location_monitor_generate_messages_cpp_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // LOCATION_MONITOR_MESSAGE_LOCATION_MONITOR_GENERATE_MESSAGES_CPP_H
