version: "3"

services:
  controller:
    container_name: 'controller'
    build:
      context: ""
      dockerfile: controller/Dockerfile
    restart: always
    volumes:
      - ./controller/controller:/app/controller/controller
    links:
      - db
    depends_on:
      - db
    # Insert your own IP in here
    ports:
      - 192.168.2.102:8765:8765
    environment:
      - PYTHONUNBUFFERED=1

  db:
    container_name: 'db'
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: turtlebot_db
      POSTGRES_HOST: db
    #      POSTGRES_HOST: 172.21.0.2
    ports:
      - 5432:5432