version: "3"

services:
  backend:
    command: tail -F anything
    container_name: 'backend'
    build:
      context: ""
      dockerfile: Dockerfile
#    volumes:
#      - ./controller:/app/controller
    links:
      - db
    depends_on:
      - db
    ports:
      - ${HOST_IP}:8765:8765
      - ${HOST_IP}:11311:11311
    environment:
      - "PYTHONUNBUFFERED=1"

  db:
    container_name: 'db'
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: turtlebot_db
      POSTGRES_HOST: db
    ports:
      - 5432:5432

#  ros:
#    command: tail -F anything
#    container_name: 'ros'
#    build:
#      context: ""
#      dockerfile: ros/Dockerfile
#    ports:
#      - ${HOST_IP}:11311:11311
