version: "3"

services:
  backend:
    command: tail -F anything
    container_name: 'backend'
    build:
#      network: host
      context: ""
      dockerfile: Dockerfile
    volumes:
      - ./backend:/home/backend
    links:
      - db
    depends_on:
      - db
    ports:
      - 8765:8765
      - 11311:11311
    environment:
      - "PYTHONUNBUFFERED=1"

  db:
    container_name: 'db'
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: turtlebot_db
      POSTGRES_HOST: db
    ports:
      - 5432:5432